### ISSUE TITLE
Python 3.7 - unable to run sample code

### ISSUE THREAD

**Issue by zizu1985** [greater-than/PipeLayer#12]
Hi,

With Python 3.7 I cannot run sample code.
I have below error:

Traceback (most recent call last):
  File "C:/Github/Python/pipelayers/app.py", line 1, in <module>
    from pipelayer import Pipeline
  File "C:\Github\Python\venv\lib\site-packages\pipelayer\__init__.py", line 6, in <module>
    from pipelayer.pipeline import Pipeline  # NOQA F401
  File "C:\Github\Python\venv\lib\site-packages\pipelayer\pipeline.py", line 10, in <module>
    from pipelayer.protocol import IFilter, IStep
  File "C:\Github\Python\venv\lib\site-packages\pipelayer\protocol.py", line 5, in <module>
    from typing import (Any, Callable, List, Optional, Protocol, Tuple,
ImportError: cannot import name 'Protocol' from 'typing' (C:\Program Files\Python\lib\typing.py)

**Comment by greater-than** [comment]
Interesting. It was developed in 3.8.3. Let me install 3.7.1 and see what's going on. Thanks for the bug report!

**Comment by greater-than** [comment]
I confirmed your error and found that the issue with Protocol is that there's a namespace difference between 3.7 and 3.8. 

I'll investigate creating a patch.

**Comment by greater-than** [comment]
This is a quick fix for the issue you reported in protocol.py if you want to temporarily make the update. Replace line 5/6 with this:
```
from typing import Any, Callable, List, Optional, Tuple
try:
    from typing import Protocol, runtime_checkable
except Exception:
    from typing_extensions import Protocol, runtime_checkable
```

I'll run some more tests to make sure this isn't the only 3.7 issue, and publish a proper patch--should be on Sat, Feb. 20th
